### ISSUE TITLE
HEC-WAT Forum

### ISSUE THREAD

**Issue by emalvarol** [HydrologicEngineeringCenter/WAT#4]
Hello,

Is there a forum where we can share doubts and problems about the operation of the software?

Thanks,

**Comment by HenryGeorgist** [comment]
Are you a USACE employee? We have a discourse site here https://discourse.hecdev.net/c/wat/7 if you have a USACE email. If not, i can open up a discussion board on this repository.

**Comment by HenryGeorgist** [comment]
Since I am not sure if you can access discourse, and no new discussions were made there, I decided to go ahead and open up a discussion page here: https://github.com/HydrologicEngineeringCenter/WAT/discussions
This discussion page should be public, so anyone interested in HEC-WAT can add to the conversation. Join in!
